### ISSUE TITLE
Example is not Working.

### ISSUE THREAD

**Issue by ajay2c9** [prynt/PryntTrimmerView#12]
Hi, 
I want to use the PryntTrimmerView in my app . while running the example it shows error "
Showing Recent Issues
“Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly." After updated that it shows same issue. i am using xcode 8.3.3

**Comment by HHK1** [comment]
Hi! 
If you’re not running Xcode9, you should not take the latest version. Try running it in version 1.0.1 which is in swift 3.

**Comment by ajay2c9** [comment]
Thank you for the reply.
