### ISSUE TITLE
How to use PryntTrimmerView in Objective-c?

### ISSUE THREAD

**Issue by ajay2c9** [prynt/PryntTrimmerView#13]
Hi,
In my project i used both objective-c code and swift code. I already implemented the AVplayer for playing the video in my app.I drag and drop all 8 PryntTrimmerView files in my project.i called the files like below .
@class AssetVideoScrollView;
@class AVAssetTimeSelector;
@class CropMaskView;
@class HandlerView;
@class PryntTrimmerView;
@class ThumbSelectorView;
@class VideoCropView;
@class VideoScrollView;

 I want to implement the code in objective-c .
I add this in .h file
@property (strong,nonatomic) IBOutlet PryntTrimmerView *trimmerView;
 after that i can't able to use the  properties and delegate methods in .m files.
 please give suggestions to implement the properties and delegate methods in .m file using objective-c . I am using xcode 8.33.3.

Thank you

**Comment by HHK1** [comment]
1. Use version 1.0.1 of the project or below as you are running on Xcode 8
2. You can copy the files, but I suggest to use a dependency manager instead. Currently we're supporting only cocoa pods: https://guides.cocoapods.org/using/getting-started.html
3. To mix swift and objective-c please follow this guide: https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html
