### ISSUE TITLE
Adjusting Start/End Handles programmatically

### ISSUE THREAD

**Issue by elementsrtyte** [prynt/PryntTrimmerView#19]
It would be very helpful to provide some methods on TrimmerView that allows us to pass in a 'start' or 'end' CMTime to TrimmerView that allows us to configure the default starting/ending times of the trimmer.

Something with a signature similar to this would be great...
```
public func updateLeftHandlePosition(time: CMTime) {
...
}
public func updateRightHandlePosition(time: CMTime) {
...
}
```

Thanks

**Comment by HHK1** [comment]
There has been a similar request here #17, so I'm going to close this issue as a duplicate.

As mentioned in the first issue: You should be able to do something similar to the positionBar. I currently don't have the time to work on this. Feel free to open a PR if you decide to implement it.
