### ISSUE TITLE
Swift 4.1 Cannot override with a stored property '...Constraint'

### ISSUE THREAD

**Issue by NikKovIos** [prynt/PryntTrimmerView#21]
```swift
class AssetVideoScrollView: UIScrollView {
    private var widthConstraint: NSLayoutConstraint?
```

and the same error with 

```swift
  @IBDesignable public class TrimmerView: AVAssetTimeSelector {
    private var leftConstraint: NSLayoutConstraint?
    private var rightConstraint: NSLayoutConstraint?
```

You can check it in https://github.com/Yummypets/YPImagePicker/commit/4fea39d9c3688a1ea8e36ae83dcce59a507c3e3d

**Comment by HHK1** [comment]
Those are stored properties, private moreover, you are not supposed to override them.

**Comment by NikKovIos** [comment]
But they are in your library https://github.com/prynt/PryntTrimmerView/blob/master/PryntTrimmerView/Classes/Trimmer/PryntTrimmerView.swift
The compiler warning on them.

**Comment by HHK1** [comment]
>But they are in your library https://github.com/prynt/PryntTrimmerView/blob/master/PryntTrimmerView/Classes/Trimmer/PryntTrimmerView.swift


The only thing I'm overriding in this class are the methods to setup the subviews and the constraints: 
`setupSubviews` and `constrainAssetPreview`. 

>The compiler warning on them.

Where ? In your project or in this library ?

**Comment by calsmith** [comment]
+1 importing the raw source files into a project (i.e. without cocoapods) causes the following build errors:
`"Cannot override with a stored property 'widthConstraint'" AssetVideoScrollView.swift line 12
`for each of the constraints in Swift 5 Xcode 12.5. Is there a workaround for this?
