### ISSUE TITLE
Great tool <3

### ISSUE THREAD

**Issue by s4cha** [prynt/PryntTrimmerView#22]
Hey @HHK1, great tool you have here !

This is a feature that was requested in our media picker and some users pointed us towards you library.
Just wanted to let you know that we are looking at integrating `PryntTrimmerView` as a dependency as part of our Media Picker tool [YPImagePicker](https://github.com/Yummypets/YPImagePicker). 

Begining implementation can be found: [here](https://github.com/Yummypets/YPImagePicker/pull/47)

Let me know how you'd feel about that :)

Cheers!

**Comment by HHK1** [comment]
Hey @s4cha ! 
The code is published with a MIT license, so there is no issue at all with that!

If you feel like referencing this library on your Readme that's up to you, but that's entirely up to you.

I see that you are using Carthage for dependencies, I've never used it in projects, but the setup didn't seem too complex so I've added a prebuilt framework to the latest release: https://github.com/prynt/PryntTrimmerView/releases
Tell me if that works for you, I'll mark the library as Carthage compatible in the Readme then.

**Comment by s4cha** [comment]
@HHK1 That's some awesome news!
Of course, once the next version will be live, we'll reference your repo on our Readme :)
Concerning Carthage, you can also upload the `.framework` inside the release as seen here: 
https://github.com/Yummypets/YPImagePicker/releases/tag/2.8.1

I was actually about to submit a PR for Carthage support so thanks a ton for thinking a bout us !

Carthage pul still l doesn't seem to work though.
Here is the log for reference:
```
MacBookPro-Sacha:test sacha$ carthage update
*** Fetching PryntTrimmerView
*** Checking out PryntTrimmerView at "2.0.1"
*** xcodebuild output can be found in /var/folders/6t/3blf7h3950gfx14v61r581wm0000gq/T/carthage-xcodebuild.i5fo7q.log
*** Skipped building PryntTrimmerView due to the error:
Dependency "PryntTrimmerView" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/prynt/PryntTrimmerView/issues/new
MacBookPro-Sacha:test sacha$
```

What I did locally for reference was go into`Edit Scheme` then `manage scheme` then check 
`PryntTrimmerView` and also cheek it as `shared`.
This makes it "visible" by Carthage.

Cheers,

**Comment by s4cha** [comment]
It looks like `xcshareddata` in the gitignore prevents us from pushing it though :)

**Comment by HHK1** [comment]
Hmm, here is what I did:

1. I did check that the scheme for the framework was shared, here is what I have:

<img width="1280" alt="screen shot 2018-04-24 at 13 47 43" src="https://user-images.githubusercontent.com/6484356/39213419-5c655dde-47c6-11e8-8efa-3803f4db7edb.png">

2. I downloaded carthage and used `carthage build --no-skip-current` which gave me the following:

```
*** xcodebuild output can be found in /var/folders/g3/_t28w37x489d84kjk6c_fkm00000gn/T/carthage-xcodebuild.7Ua6eq.log
*** Building scheme "PryntTrimmerView" in PryntTrimmerView.xcworkspace
*** Building scheme "PryntTrimmerView" in PryntTrimmerView.xcworkspace
```

3. I then ran `carthage archive PryntTrimmerView` to archive the framework. 

Got this from the terminal:

````
*** Found Carthage/Build/iOS/PryntTrimmerView.framework
*** Found Carthage/Build/iOS/PryntTrimmerView.framework.dSYM
*** Found Carthage/Build/iOS/1AB5664E-2FF1-3A15-93E8-009B0CC46950.bcsymbolmap
*** Found Carthage/Build/iOS/D89DDCCF-7515-39FC-A978-1C09A1E7BE26.bcsymbolmap
*** Found Carthage/Build/iOS/38BB924E-4197-38C0-9E2B-081283FE3D51.bcsymbolmap
*** Found Carthage/Build/iOS/45449960-B848-3087-88AB-138355679028.bcsymbolmap
*** Created PryntTrimmerView.framework.zip
````

4. I made a commit, tagged and pushed to this repo under release 2.0.1

I'm going to try installing the dependency in a dummy projet, see what happens. In the meantime:

- If you notice anything blatantly wrong in the above, just tell me and I'll fix it.
- If you have a working branch that is carthage compatible, you can open a pull request

**Comment by s4cha** [comment]
@HHK1 I think the missing thing is just manually uploading the '.framework' in the release on GitHub.

Question, when you shared the `PryntTrimmerView`, did it show in git? If you want Carthage support to work without having to manually upload a `.framework`, we'll need to have the shared scheme setting pushed to GitHub.

Hope that helps,

**Comment by HHK1** [comment]
I've uploaded the .framework.zip in the release, does it work for you ? 
I'm looking at pushing the schemes changes to git, it seems that indeed they are not taken into account

**Comment by s4cha** [comment]
Awesome! `carthage update` works because it's smart enough to take the pre-built framework when available. For the "classic" integration, you can run `carthage update --no-use-binaries`. This one will work when we sort the share scheme thing out. No rush I can help you with that later if you want :)

**Comment by HHK1** [comment]
@s4cha I think it's because the scheme is part of the Pods project. I'm recreating a target that should be visible to Carthage

**Comment by HHK1** [comment]
@s4cha I've updated the project to include a shared scheme that is not in the Pods .xcodeproj
Updating the dependencies on a dummy project using the `--no-use-binaries` flag is working on my end. Tell me if it's good for you, and I'll add the carthage compatibility on the readme, and I'll close this issue.

**Comment by s4cha** [comment]
@HHK1 it now works perfectly 👌
