### ISSUE TITLE
Video quality changed after crop done

### ISSUE THREAD

**Issue by nitingohel** [prynt/PryntTrimmerView#23]
As i testing this lib i did not change anything in exisitng code but i found that video quality change after crop done as there used:
`
 let exportSession = AVAssetExportSession(asset: assetComposition, presetName: AVAssetExportPresetHighestQuality)`

Can you please tel me where do i change to get same quality after crop done.

**Comment by HHK1** [comment]
@nitingohel The goal of this library is to provide only the controls to do the trimming and the cropping.
The actual cropping / trimming of your video asset is up to you, the example is only here to provide one possible implementation.

In the example provided, you need to change the `renderSize` to keep the same quality as the original.
