### ISSUE TITLE
How to get the trimmed video from this delegate 'didChangePositionBar'

### ISSUE THREAD

**Issue by prithiviraj** [prynt/PryntTrimmerView#27]
Can you please help me how to get the trimmed video from this delegate 'didChangePositionBar'

**Comment by HHK1** [comment]
Hi @prithiviraj. `didChangePositionBar` is a delegate method to help you synchronise your video player with the trimmer. 
Also, this library does not make the work of trimming the video for you. Please refer to the readme and the example app if you don't know how to do this.

>Access the startTime and endTime property to know where to trim your asset. You can use the TrimmerViewDelegate to link the trimmer with an AVPlayer and provide the end user with a preview. See the VideoTrimmerViewController inside the project to see an example.
