### ISSUE TITLE
Is there a time limit on the trimmerView video length? 

### ISSUE THREAD

**Issue by AlexMarshall12** [prynt/PryntTrimmerView#28]
When I import videos over 15 seconds, it crops to 15 seconds. I don't see this mentioned anywhere. Is this an actual limitation or am I doing something wrong? I just used the Example in this repo with the trimmerView (finding a random video on my phone that is > 15 sec)

**Comment by HHK1** [comment]
https://github.com/prynt/PryntTrimmerView/issues/26
