### ISSUE TITLE
Suggestion : Load the whole video thumbnail without scrolling.

### ISSUE THREAD

**Issue by ram2386** [prynt/PryntTrimmerView#6]
Thanks for sharing the code for trimming the video.

Could we provide the same functionality as in existing Apple's photo trimming tool which loads the video without scrolling?

Please let me know if we can accommodate this changes in the existing code so it will be more useful tool.

**Comment by HHK1** [comment]
I think you can achieve this by using the `maxDuration` on the `TrimmerView`.

The maxDuration is the max duration of the asset that will be shown at once, i.e. without scrolling. 
If it's smaller than the length of the asset, no scrolling will be necessary.

Make sure to set it before setting the asset, as setting the assets will regenerate all the thumbnails.

**Comment by HHK1** [comment]
Does this solve your issue @ram2386 ?

**Comment by ram2386** [comment]
Thanks for the reply, I had tried your solution but it does not work for me, so I had used the default controller of UIVideoEditorController which provide the same UI as Apple does for Photos app.
