### ISSUE TITLE
Lag when trimming the video in iOS11

### ISSUE THREAD

**Issue by RobSwish** [prynt/PryntTrimmerView#8]
I know it's still in beta, but it is not in beta 7 which is quite far along and the trimmer still lags. Please can you fix this asap?

**Comment by sparga** [comment]
With the example project, I tested both the Trimmer and the Cropper on an a device and the simulator and the performance is similar to iOS 10.
Could you give more details on how to reproduce?

**Comment by HHK1** [comment]
@RobSwish Any update on this ?
